/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abcsecuritycompanysystem;

import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Sanele
 */
public class frmReports extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReports
     */
    public frmReports() {
        initComponents();
    }
    
    //Instantiation of objects of class clsDatabaseConnection, and
    //class clsSQLMethods.
    clsDatabaseConnection clsConnect = new clsDatabaseConnection();
    clsQueryingMethods clsSQLMethods = new clsQueryingMethods();
    
    //A method that returns as string a query that retrieves
    //from database all security personnel details.
    private String mViewStaffReportQuery()
    {
        return "SELECT ID, Name, DateOfBirth, Gender, Password, AddedBy, Level FROM tblUsers "
                + "WHERE Level = 'security'";
    }
    
    //A method that returns as string a query that generates
    //actionable information about client registered complaints.
    private String mViewComplaintsReportQuery()
    {
        return "SELECT "+clsSQLMethods.mGetID("SELECT COUNT(*) FROM tblComplaints "
                + "WHERE datediff(NOW(), DateAndTime) <= '7'")+" AS Complaints_This_Week, "+
                clsSQLMethods.mGetID("SELECT COUNT(*) FROM tblComplaints "
                        + "WHERE AreaOfIncident LIKE '%Sandhurst%'")+" AS Complaints_In_SANDHURST, "+
                clsSQLMethods.mGetID("SELECT COUNT(*) FROM tblComplaints "
                        + "WHERE AreaOfIncident LIKE '%Inanda%'")+" As Complaints_In_INANDA, "+
                clsSQLMethods.mGetID("SELECT COUNT(*) FROM tblComplaints "
                        + "WHERE AreaOfIncident LIKE '%Parkhurst%'")+" AS Complaints_In_PARKHURST";
    }
    
    //A method that display report information in tabular format.
    private void mViewReports(String strQuery)
    {
        try
        {
            try (Statement stSQLQuery = clsConnect.mConnectToDatabaseABCSecurity().prepareStatement(strQuery)) {
                ResultSet rs = stSQLQuery.executeQuery(strQuery);
                ResultSetMetaData rsmt = rs.getMetaData();
                int intColumnCount = rsmt.getColumnCount();
                Vector vColumn = new Vector(intColumnCount);
                for(int i = 1; i <= intColumnCount; i++)
                {
                    vColumn.add(rsmt.getColumnName(i));
                }   Vector vData = new Vector();
                Vector vRow = new Vector();
                while(rs.next())
                {
                    vRow = new Vector(intColumnCount);
                    for(int i = 1; i <= intColumnCount; i++)
                    {
                        vRow.add(rs.getObject(i));
                    }
                    vData.add(vRow);
                }   JPanel pnlTable = new JPanel();
                JTable tblMembers = new JTable(vData, vColumn);
                tblMembers.setFillsViewportHeight(true);
                JScrollPane jspMemberPane = new JScrollPane(tblMembers);
                tblMembers.setVisible(true);
                tblMembers.validate();
                pnlTable.setLayout(new GridLayout(1,0));
                pnlTable.add(jspMemberPane);
                this.setResizable(true);
                this.setContentPane(pnlTable);
                stSQLQuery.close();
                rs.close();
            }
        }
        catch(SQLException eX)
        {
            JOptionPane.showMessageDialog(null, "Technical Error, table cannot be displayed"+""+eX);
        }
    }
    
    //A method that invokes methods that make it possible 
    //to view staff report.
    public void mViewStaffReport()
    {
        mViewReports(mViewStaffReportQuery());
    }
    
    //A method that invokes methods that make it possible 
    //to view Complaints report.
    public void mViewComplaintsReport()
    {
        mViewReports(mViewComplaintsReportQuery());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}